// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlqzrdcrxkspztriwaie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1scXpyZGNyeGtzcHp0cml3YWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjY2NjIsImV4cCI6MjA2NTU0MjY2Mn0.T8_rBvSeebjx54FJeFIFMu_HuOLELMCGf1xfV49iz5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);